-- Create skill_levels lookup table
create table if not exists public.skill_levels (
  id int4 primary key generated by default as identity,
  name text not null unique,
  slug text not null unique,
  description text null
);

-- Create join table between groups and skill_levels
create table if not exists public.group_x_skill_levels (
  group_id uuid not null references public.groups(id) on delete cascade,
  skill_level_id int4 not null references public.skill_levels(id) on delete restrict,
  primary key (group_id, skill_level_id)
);

-- Helpful indexes
create index if not exists idx_group_x_skill_levels_group on public.group_x_skill_levels(group_id);
create index if not exists idx_group_x_skill_levels_level on public.group_x_skill_levels(skill_level_id);

-- Seed defaults if table empty
insert into public.skill_levels (name, slug, description)
select * from (values
  ('Beginner', 'beginner', 'New riders or casual pace'),
  ('Intermediate', 'intermediate', 'Some experience, steady pace'),
  ('Advanced', 'advanced', 'Experienced riders, faster pace'),
  ('All Levels', 'all-levels', 'Open to all skill levels')
) as v(name, slug, description)
where not exists (select 1 from public.skill_levels);
;
