create extension if not exists vector;
create extension if not exists pg_trgm;

alter table public.learn_articles
	add column if not exists tags jsonb not null default '[]'::jsonb,
	add column if not exists audience jsonb not null default '[]'::jsonb,
	add column if not exists difficulty_level text not null default 'all-levels',
	add column if not exists ride_type text not null default 'mixed',
	add column if not exists geo_scope text not null default 'global',
	add column if not exists geo_city text,
	add column if not exists geo_state text,
	add column if not exists content_type text not null default 'reference',
	add column if not exists is_evergreen boolean not null default true,
	add column if not exists metadata_confidence numeric(4, 2) not null default 0.50,
	add column if not exists search_document tsvector,
	add column if not exists article_embedding vector(64),
	add column if not exists search_updated_at timestamptz;

alter table public.learn_article_revisions
	add column if not exists tags jsonb not null default '[]'::jsonb,
	add column if not exists audience jsonb not null default '[]'::jsonb,
	add column if not exists difficulty_level text not null default 'all-levels',
	add column if not exists ride_type text not null default 'mixed',
	add column if not exists geo_scope text not null default 'global',
	add column if not exists geo_city text,
	add column if not exists geo_state text,
	add column if not exists content_type text not null default 'reference',
	add column if not exists is_evergreen boolean not null default true,
	add column if not exists metadata_confidence numeric(4, 2) not null default 0.50;

alter table public.learn_articles
	drop constraint if exists learn_articles_difficulty_level_check,
	drop constraint if exists learn_articles_geo_scope_check,
	drop constraint if exists learn_articles_metadata_confidence_check;

alter table public.learn_articles
	add constraint learn_articles_difficulty_level_check
		check (difficulty_level in ('all-levels', 'beginner', 'intermediate', 'advanced')),
	add constraint learn_articles_geo_scope_check
		check (geo_scope in ('global', 'national', 'state', 'metro', 'city', 'neighborhood', 'route-specific')),
	add constraint learn_articles_metadata_confidence_check
		check (metadata_confidence >= 0 and metadata_confidence <= 1);

create index if not exists learn_articles_search_document_idx
	on public.learn_articles using gin (search_document);

create index if not exists learn_articles_tags_idx
	on public.learn_articles using gin (tags);

create index if not exists learn_articles_geo_idx
	on public.learn_articles (geo_scope, geo_state, geo_city);

create index if not exists learn_articles_content_type_idx
	on public.learn_articles (content_type, is_evergreen, updated_at desc);

create index if not exists learn_articles_embedding_idx
	on public.learn_articles using ivfflat (article_embedding vector_cosine_ops)
	with (lists = 64);

create table if not exists public.learn_article_chunks (
	id uuid primary key default gen_random_uuid(),
	article_id uuid not null references public.learn_articles (id) on delete cascade,
	chunk_index integer not null,
	heading text,
	chunk_text text not null,
	chunk_chars integer not null default 0,
	tags jsonb not null default '[]'::jsonb,
	search_document tsvector,
	embedding vector(64),
	created_by_user_id uuid references auth.users (id) on delete set null,
	updated_by_user_id uuid references auth.users (id) on delete set null,
	created_at timestamptz not null default timezone('utc', now()),
	updated_at timestamptz not null default timezone('utc', now()),
	constraint learn_article_chunks_article_chunk_unique unique (article_id, chunk_index)
);

create index if not exists learn_article_chunks_article_idx
	on public.learn_article_chunks (article_id, chunk_index asc);

create index if not exists learn_article_chunks_search_document_idx
	on public.learn_article_chunks using gin (search_document);

create index if not exists learn_article_chunks_embedding_idx
	on public.learn_article_chunks using ivfflat (embedding vector_cosine_ops)
	with (lists = 64);

create table if not exists public.learn_article_feedback_events (
	id bigint generated by default as identity primary key,
	created_at timestamptz not null default timezone('utc', now()),
	user_id uuid references auth.users (id) on delete set null,
	session_id text,
	article_id uuid not null references public.learn_articles (id) on delete cascade,
	chunk_id uuid references public.learn_article_chunks (id) on delete set null,
	feedback_type text not null,
	dwell_seconds integer,
	context jsonb not null default '{}'::jsonb,
	constraint learn_article_feedback_type_check
		check (feedback_type in ('impression', 'click', 'dwell', 'save', 'hide'))
);

create index if not exists learn_article_feedback_events_article_idx
	on public.learn_article_feedback_events (article_id, created_at desc);

create index if not exists learn_article_feedback_events_user_idx
	on public.learn_article_feedback_events (user_id, created_at desc);

create index if not exists learn_article_feedback_events_session_idx
	on public.learn_article_feedback_events (session_id, created_at desc);

create table if not exists public.learn_article_user_weights (
	user_id uuid primary key references auth.users (id) on delete cascade,
	lexical_weight numeric(4, 3) not null default 0.280,
	semantic_weight numeric(4, 3) not null default 0.320,
	freshness_weight numeric(4, 3) not null default 0.150,
	personalization_weight numeric(4, 3) not null default 0.170,
	location_weight numeric(4, 3) not null default 0.080,
	diversity_weight numeric(4, 3) not null default 0.060,
	updated_at timestamptz not null default timezone('utc', now()),
	constraint learn_article_user_weights_nonnegative
		check (
			lexical_weight >= 0
			and semantic_weight >= 0
			and freshness_weight >= 0
			and personalization_weight >= 0
			and location_weight >= 0
			and diversity_weight >= 0
		)
);

create or replace function public.learn_jsonb_array_to_text(source jsonb)
returns text
language sql
immutable
as $$
	select coalesce(string_agg(value, ' '), '')
	from jsonb_array_elements_text(coalesce(source, '[]'::jsonb)) as t(value);
$$;

create or replace function public.learn_prepare_article_search_document()
returns trigger
language plpgsql
set search_path = public
as $$
begin
	new.search_document := to_tsvector(
		'english',
		coalesce(new.title, '') || ' ' ||
		coalesce(new.summary, '') || ' ' ||
		coalesce(new.category_name, '') || ' ' ||
		coalesce(new.subcategory_name, '') || ' ' ||
		coalesce(new.body_markdown, '') || ' ' ||
		coalesce(new.reader_summary, '') || ' ' ||
		public.learn_jsonb_array_to_text(new.key_takeaways) || ' ' ||
		public.learn_jsonb_array_to_text(new.tags) || ' ' ||
		public.learn_jsonb_array_to_text(new.audience) || ' ' ||
		coalesce(new.difficulty_level, '') || ' ' ||
		coalesce(new.ride_type, '') || ' ' ||
		coalesce(new.content_type, '') || ' ' ||
		coalesce(new.geo_scope, '') || ' ' ||
		coalesce(new.geo_city, '') || ' ' ||
		coalesce(new.geo_state, '')
	);
	new.search_updated_at := timezone('utc', now());
	return new;
end;
$$;

create or replace function public.learn_prepare_article_chunk()
returns trigger
language plpgsql
set search_path = public
as $$
begin
	if tg_op = 'INSERT' then
		new.created_at := coalesce(new.created_at, timezone('utc', now()));
		new.updated_at := coalesce(new.updated_at, new.created_at);
	else
		new.created_at := old.created_at;
		new.updated_at := timezone('utc', now());
	end if;

	new.chunk_chars := greatest(0, char_length(coalesce(new.chunk_text, '')));
	new.search_document := to_tsvector(
		'english',
		coalesce(new.heading, '') || ' ' ||
		coalesce(new.chunk_text, '') || ' ' ||
		public.learn_jsonb_array_to_text(new.tags)
	);

	return new;
end;
$$;

create or replace function public.learn_prepare_user_weights()
returns trigger
language plpgsql
set search_path = public
as $$
begin
	new.updated_at := timezone('utc', now());
	return new;
end;
$$;

create or replace function public.learn_snapshot_article_revision()
returns trigger
language plpgsql
set search_path = public
as $$
begin
	insert into public.learn_article_revisions (
		article_id,
		revision_number,
		created_at,
		created_by_user_id,
		title,
		slug,
		summary,
		body_markdown,
		editor_mode,
		category_slug,
		category_name,
		subcategory_slug,
		subcategory_name,
		import_source_path,
		cover_image_url,
		reader_summary,
		key_takeaways,
		tags,
		audience,
		difficulty_level,
		ride_type,
		geo_scope,
		geo_city,
		geo_state,
		content_type,
		is_evergreen,
		metadata_confidence
	) values (
		new.id,
		new.last_revision_number,
		new.updated_at,
		case
			when tg_op = 'INSERT' then new.created_by_user_id
			else new.updated_by_user_id
		end,
		new.title,
		new.slug,
		new.summary,
		new.body_markdown,
		new.editor_mode,
		new.category_slug,
		new.category_name,
		new.subcategory_slug,
		new.subcategory_name,
		new.import_source_path,
		new.cover_image_url,
		new.reader_summary,
		coalesce(new.key_takeaways, '[]'::jsonb),
		coalesce(new.tags, '[]'::jsonb),
		coalesce(new.audience, '[]'::jsonb),
		coalesce(new.difficulty_level, 'all-levels'),
		coalesce(new.ride_type, 'mixed'),
		coalesce(new.geo_scope, 'global'),
		new.geo_city,
		new.geo_state,
		coalesce(new.content_type, 'reference'),
		coalesce(new.is_evergreen, true),
		coalesce(new.metadata_confidence, 0.50)
	);

	return new;
end;
$$;

drop trigger if exists learn_prepare_article_search_document on public.learn_articles;
create trigger learn_prepare_article_search_document
	before insert or update on public.learn_articles
	for each row
	execute function public.learn_prepare_article_search_document();

drop trigger if exists learn_prepare_article_chunk on public.learn_article_chunks;
create trigger learn_prepare_article_chunk
	before insert or update on public.learn_article_chunks
	for each row
	execute function public.learn_prepare_article_chunk();

drop trigger if exists learn_prepare_user_weights on public.learn_article_user_weights;
create trigger learn_prepare_user_weights
	before update on public.learn_article_user_weights
	for each row
	execute function public.learn_prepare_user_weights();

update public.learn_articles
set updated_at = updated_at
where search_document is null;

alter table public.learn_article_chunks enable row level security;
alter table public.learn_article_feedback_events enable row level security;
alter table public.learn_article_user_weights enable row level security;

create policy "learn_article_chunks_select_visible"
	on public.learn_article_chunks
	for select
	to anon, authenticated
	using (
		exists (
			select 1
			from public.learn_articles
			where id = article_id
				and (is_published = true or auth.uid() is not null)
		)
	);

create policy "learn_article_chunks_insert_authenticated"
	on public.learn_article_chunks
	for insert
	to authenticated
	with check (auth.uid() is not null);

create policy "learn_article_chunks_update_authenticated"
	on public.learn_article_chunks
	for update
	to authenticated
	using (auth.uid() is not null)
	with check (auth.uid() is not null);

create policy "learn_article_chunks_delete_authenticated"
	on public.learn_article_chunks
	for delete
	to authenticated
	using (auth.uid() is not null);

create policy "learn_article_feedback_events_insert_public"
	on public.learn_article_feedback_events
	for insert
	to anon, authenticated
	with check (
		(article_id is not null)
		and (
			(user_id is null and auth.uid() is null)
			or (auth.uid() is not null and user_id = auth.uid())
		)
	);

create policy "learn_article_feedback_events_select_owner"
	on public.learn_article_feedback_events
	for select
	to authenticated
	using (user_id = auth.uid() or public.is_learn_admin());

create policy "learn_article_user_weights_select_owner"
	on public.learn_article_user_weights
	for select
	to authenticated
	using (user_id = auth.uid() or public.is_learn_admin());

create policy "learn_article_user_weights_insert_owner"
	on public.learn_article_user_weights
	for insert
	to authenticated
	with check (user_id = auth.uid());

create policy "learn_article_user_weights_update_owner"
	on public.learn_article_user_weights
	for update
	to authenticated
	using (user_id = auth.uid() or public.is_learn_admin())
	with check (user_id = auth.uid() or public.is_learn_admin());
